http:
  host: localhost
  port: 8080

ftp:
  host: "webhome.cc.iitk.ac.in"
  port: 21
  enabled: false

jwt:
  secret: "corridor-earthlike-defection"

admin:
  username: "ssaha"

candidates:
  - "milindl"
  - "yashsriv"

redis:
  network: tcp
  host: localhost
  port: 6379
  pool: 10

wallet:
  filename: "/home/milind/.ethereum/keystore/UTC--2019-04-15T11-22-20.154376847Z--7d8bb646b1373376710ce63ff78a091d97af8e98"
  password: "mywalletpassword"

ethclient:
  location: "https://ropsten.infura.io/v3/a34a52c7894e4852a4152d53bb9b9fd9"

# contract:
  # address: "0xd6bf419Eb5b0b46C6Aa1A435e69aE5498Ad7D4EF"
